// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJjhjZLZvlwB-8zOJtXZHMykVoUdZBFs',
    appId: '1:437547043062:web:64c94f1c148fa65bf6c4d7',
    messagingSenderId: '437547043062',
    projectId: 'sample-2bc88',
    authDomain: 'sample-2bc88.firebaseapp.com',
    storageBucket: 'sample-2bc88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIB87RmvKNXMxlE2JFk6W797Asg6H-Hj0',
    appId: '1:437547043062:android:3aae5f47946ed019f6c4d7',
    messagingSenderId: '437547043062',
    projectId: 'sample-2bc88',
    storageBucket: 'sample-2bc88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKIBIeCaAnJVbAsNmC65eJWQs4HxVDeh4',
    appId: '1:437547043062:ios:98a854fbf7a47386f6c4d7',
    messagingSenderId: '437547043062',
    projectId: 'sample-2bc88',
    storageBucket: 'sample-2bc88.appspot.com',
    androidClientId: '437547043062-6ic4n5tllftc7uf21llhg50nnopfe0fi.apps.googleusercontent.com',
    iosClientId: '437547043062-mcpe1sg7agv3u6321nsl5jdcs06t9l49.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKIBIeCaAnJVbAsNmC65eJWQs4HxVDeh4',
    appId: '1:437547043062:ios:7a7ebca052b85928f6c4d7',
    messagingSenderId: '437547043062',
    projectId: 'sample-2bc88',
    storageBucket: 'sample-2bc88.appspot.com',
    androidClientId: '437547043062-6ic4n5tllftc7uf21llhg50nnopfe0fi.apps.googleusercontent.com',
    iosClientId: '437547043062-dfkkhlk3p39itih42k300kef6utfrk44.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleProject.RunnerTests',
  );
}
